openapi: 3.0.0

info:
  version: '1.0'
  title: 'LBAW MineMax Web API'
  description: 'Web Resources Specification (A7) for MineMax'

servers:
- url: http://lbaw.fe.up.pt
  description: Production server

externalDocs:
  description: Find more info here.
  url: https://git.fe.up.pt/lbaw/lbaw2324/lbaw2314

tags:
- name: 'M01: Authentication and Individual Profile'


